AddonId: VNDBMetadata
Packages:
  - Version: 2.1
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2022-08-19
    PackageUrl: https://github.com/Mithnar/PlayniteVndb/releases/download/2.1/PlayniteVndb_2_1.pext
    Changelog:
      - Option to ignore fields
      - Option to include an estimated playtime tag
